version: '3.8'

services:
  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
      - /app/frontend/node_modules
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT:-8000}
      - VITE_REDIRECT_URL=http://localhost:${REDIRECT_PORT:-8001}
    depends_on:
      - backend
    networks:
      - linkpipe-network

  # Backend API (Node.js/Express to simulate Lambda locally)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - /app/backend/node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - dynamodb-local
    networks:
      - linkpipe-network

  # Redirect Service (separate service for handling short URLs)
  redirect-service:
    build:
      context: .
      dockerfile: backend/Dockerfile.redirect
    ports:
      - "${REDIRECT_PORT:-8001}:8001"
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - /app/backend/node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - dynamodb-local
    networks:
      - linkpipe-network

  # DynamoDB Local for development
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: linkpipe-dynamodb-local
    ports:
      - "${DYNAMODB_PORT:-8002}:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - linkpipe-network

  # DynamoDB Admin UI (optional)
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: linkpipe-dynamodb-admin
    ports:
      - "${DYNAMODB_ADMIN_PORT:-8003}:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - dynamodb-local
    networks:
      - linkpipe-network

volumes:
  dynamodb-data:

networks:
  linkpipe-network:
    driver: bridge 